#!/bin/bash

# Welcome to the thoughtbot laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

export BASEDIR=$(dirname $0)
export LIB_FUNCTIONS="${BASEDIR}/lib/functions.sh"
source $LIB_FUNCTIONS

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e


if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    export PATH="/usr/local/bin:$PATH"
else
  fancy_echo "Homebrew already installed. Skipping ..."
fi

fancy_echo "Updating Homebrew formulas ..."
brew update

brew_install_or_upgrade 'git'
brew_install_or_upgrade 'jq'
brew_install_or_upgrade 'openssl'
brew_install_or_upgrade 'wget'
brew_install_or_upgrade 'httpie'
brew_install_or_upgrade 'sysdig'
brew_install_or_upgrade 'gnu-sed' '--with-default-names'
brew_install_or_upgrade 'the_silver_searcher'
brew_install_or_upgrade 'vim' '--with-lua'
brew_install_or_upgrade 'ctags'
brew_install_or_upgrade 'tmux'
brew_install_or_upgrade 'reattach-to-user-namespace'
brew_install_or_upgrade 'hub'

brew_install_or_upgrade 'python'
brew_install_or_upgrade 'pyenv'
brew_install_or_upgrade 'pyenv-virtualenv'
brew_install_or_upgrade 'rbenv'
brew_install_or_upgrade 'ruby-build'
brew_install_or_upgrade 'glide'
brew_install_or_upgrade 'direnv'

brew_install_or_upgrade 'ssh-copy-id'
brew_install_or_upgrade 'pwgen'
brew_install_or_upgrade 'docker'
brew_install_or_upgrade 'ansible'
brew_install_or_upgrade 'kubernetes-cli'
brew_install_or_upgrade 'packer'
brew_install_or_upgrade 'terraform'
brew_install_or_upgrade 'vault'

brew_install_or_upgrade 'libyaml'

brew_tap 'homebrew/dupes'
brew_install_or_upgrade 'rsync'

brew_tap 'caskroom/cask'
brew_install_or_upgrade 'brew-cask'
brew_cask_install 'iterm2'
brew_cask_install 'java'
brew_cask_install 'virtualbox'
brew_cask_install 'vagrant'
brew_cask_install 'atom'

find_latest_ruby() {
  rbenv install -l | grep -v - | tail -1 | sed -e 's/^ *//'
}

ruby_version="$(find_latest_ruby)"

eval "$(rbenv init -)"

if ! rbenv versions | grep -Fq "$ruby_version"; then
  RUBY_CONFIGURE_OPTS=--with-openssl-dir=/usr/local/opt/openssl rbenv install -s "$ruby_version"
fi

rbenv local "$ruby_version"
rbenv global "$ruby_version"
rbenv shell "$ruby_version"
gem update --system
gem_install_or_update 'bundler'

fancy_echo "Configuring Bundler ..."
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))

if ! command -v rcup >/dev/null; then
  brew_tap 'thoughtbot/formulae'
  brew_install_or_upgrade 'rcm'
fi

if [ -f "$HOME/.install.local" ]; then
  . "$HOME/.install.local"
fi

git_clone_or_update $HOME/.bash_it https://github.com/Bash-it/bash-it.git
git_clone_or_update $HOME/dotfiles https://github.com/yvigara/dotfiles.git
git_clone_or_update $HOME/nerd-fonts https://github.com/ryanoasis/nerd-fonts.git
$HOME/nerd-fonts/install.sh
git_clone_or_update $HOME/gruvbox-generalized https://github.com/morhetz/gruvbox-generalized.git

go get -u github.com/nsf/gocode
go get -u github.com/jstemmer/gotags

go get -u github.com/alecthomas/gometalinter
go get -u golang.org/x/tools/cmd/goimports
go get -u github.com/rogpeppe/godef
go get -u golang.org/x/tools/cmd/oracle
go get -u golang.org/x/tools/cmd/gorename
go get -u github.com/golang/lint/golint
go get -u github.com/kisielk/errcheck

env RCRC=$HOME/dotfiles/rcrc rcup
