#!/bin/bash

# Welcome to the thoughtbot laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

export BASEDIR=$(dirname $0)
export LIB_FUNCTIONS="${BASEDIR}/lib/functions.sh"
source $LIB_FUNCTIONS

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e


if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    export PATH="/usr/local/bin:$PATH"
else
  fancy_echo "Homebrew already installed. Skipping ..."
fi

fancy_echo "Updating Homebrew formulas ..."
brew tap Homebrew/bundle
brew update
brew bundle
brew cleanup -s
brew cask cleanup

if [ -f "$HOME/.install.local" ]; then
  . "$HOME/.install.local"
fi

git_clone_or_update $HOME/.bash_it https://github.com/Bash-it/bash-it.git
git_clone_or_update $HOME/dotfiles https://github.com/yvigara/dotfiles.git
git_clone_or_update $HOME/gruvbox-generalized https://github.com/morhetz/gruvbox-generalized.git

mkdir -p $HOME/golang
go get -u github.com/nsf/gocode
go get -u github.com/jstemmer/gotags

go get -u golang.org/x/tools/cmd/goimports
go get -u github.com/rogpeppe/godef
go get -u golang.org/x/tools/cmd/guru
go get -u golang.org/x/tools/cmd/gorename
go get -u golang.org/x/lint/golint
go get -u github.com/kisielk/errcheck
go get -u github.com/frairon/go-outline-parser

go get -u github.com/uw-labs/strongbox

go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
go get -u golang.org/x/tools/cmd/gopls

npm install -g yaml-language-server
npm install -g neovim

# Create Neovim Virtual Env
xcode-select --install
CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install 3.7.5
pyenv virtualenv system neovim2
pyenv virtualenv 3.7.5 neovim3

pyenv activate neovim2
pip install --upgrade pip
pip install --upgrade pynvim
pip install --upgrade 'python-language-server[all]'

pyenv activate neovim3
pip install --upgrade pip
pip install --upgrade pynvim
pip install --upgrade 'python-language-server[all]'
pip install --upgrade ansible
pip install --upgrade flake8

pyenv deactivate

# Specify the preferences directory
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/dotfiles/iterm2_profile/"
# Tell iTerm2 to use the custom preferences in the directory
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

stow -R vim git bash

bash-it enable plugin direnv go pyenv
bash-it enable alias ag general git osx
bash-it enable completion bash-it brew defaults docker git go kubectl packer ssh system terraform vagrant vault virtualbox
