-- Customize Mason

---@type LazySpec
return {
  -- use mason-tool-installer for automatically installing Mason packages
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    -- overrides `require("mason-tool-installer").setup(...)`
    opts = {
      -- Make sure to use the names found in `:Mason`
      -- Registry: https://mason-registry.dev/registry/list
      ensure_installed = {
        "actionlint",
        "ansible-lint",
        "ansible-language-server",
        "astro-language-server",
        "basedpyright",
        "bash-language-server",
        "biome",
        "buf",
        "cmake-language-server",
        "cmakelint",
        "commitlint",
        "copilot-language-server",
        "css-lsp",
        "css-variables-language-server",
        "debugpy",
        "delve",
        "docker-language-server",
        "dotenv-linter",
        "eslint-lsp",
        "eslint_d",
        "gh-actions-language-server",
        "go-debug-adapter",
        "golangci-lint-langserver",
        "golangci-lint",
        "gopls",
        "grammarly-languageserver",
        "helm-ls",
        "html-lsp",
        "jq-lsp",
        "js-debug-adapter",
        "json-lsp",
        "jsonlint",
        "kube-linter",
        "lua-language-server",
        "markdownlint",
        "oxlint",
        "prettier",
        "protolint",
        -- "protols",
        "sqls",
        "stylua",
        "tailwindcss-language-server",
        "terraform-ls",
        "tflint",
        "tree-sitter-cli",
        "typescript-language-server",
        "vim-language-server",
        "yaml-language-server",
        "yamlfmt",
        "yamllint",
      },
    },
  },
}
