-- Customize Treesitter

---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "astro",
      "bash",
      "cmake",
      "css",
      "dockerfile",
      "editorconfig",
      "git_config",
      "gitattributes",
      "gitignore",
      "go",
      "gomod",
      "gotmpl",
      "gowork",
      "graphql",
      "hcl",
      "helm",
      "html",
      "java",
      "javascript",
      "jq",
      "json",
      "json5",
      "kcl",
      "lua",
      "make",
      "markdown",
      "promql",
      "proto",
      "python",
      "regex",
      "sql",
      "ssh_config",
      "terraform",
      "toml",
      "typescript",
      "vim",
      "xml",
      "yaml",
    },
  },
}
