[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
pin = true
lockfile = true
trusted_config_paths = ["{{ env.XDG_PROJECTS_DIR }}"]
env_cache = true
minimum_release_age = "2d"

[settings.github]
gh_cli_tokens = true
oauth_client_id = "Iv23liX49yGQdh8FIgC4"
oauth_export_env = ""

[settings.go]
set_gobin = false
set_goroot = true

[settings.npm]
package_manager = "aube"

[settings.node]
compile = false

[settings.python]
compile = false
uv_venv_auto = "create|source"

[settings.ruby]
compile = false

[tools]
node = "26"
"npm:defuddle" = "0.19.2"
"npm:@cometix/ccline" = "1.1.2"
uv = "latest"
"npm:@tobilu/qmd" = { version = "2.5.3", allow_builds = ["better-sqlite3"] }
"npm:@rivolink/leaf" = { version = "1.27.0", aube_args = "--allow-low-downloads" }
pitchfork = { version = "2.20.0", postinstall = "pitchfork boot enable" }
"npm:gitnexus" = { version = "1.6.9", allow_builds = ["@ladybugdb/core"] }
aube = "1.38.0"
"npm:@firecrawl/anydoc" = "0.1.7"
