# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](purple)\
$username\
$hostname\
[ ](fg:purple bg:blue)\
$directory\
[ ](fg:blue bg:yellow)\
$git_branch\
$git_status\
[ ](fg:yellow bg:green)\
$golang\
$nodejs\
$python\
$terraform\
[ ](fg:green)\
"""

right_format = """
$status\
[\ue0b2](fg:purple )\
$kubernetes\
[\ue0b4](fg:purple )\
"""
# Disable the blank line at the start of the prompt
add_newline = false
continuation_prompt = "[ ](fg:green)"
command_timeout = 750

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = false
style_user = "bg:purple fg:bright-white"
style_root = "bold bg:purple"
format = '[ $user]($style)'

[hostname]
ssh_only = true
format = "[@$hostname ](bg:purple)"
disabled = false


[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"
error_symbol = "[](bold red) "
#success_symbol = "[](green) "

[directory]
style = "bg:blue bold "
format = "[$path ]($style)[$read_only]($read_only_style)"
read_only = " "
read_only_style = "bg:blue fg:bright-yellow"
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:yellow fg:black"
format = '[$symbol $branch ]($style)'

[git_status]
style = "bg:yellow fg:black"
diverged = "⇕⇡${ahead_count} ⇣${behind_count}"
format = '[$ahead_behind$modified$staged$untracked$conflicted ]($style)'

conflicted ="=${count}"
ahead=	"⇡${count}"
behind ="⇣${count}"
up_to_date =""
untracked=	"?${count}"
stashed=	"$"
modified=	"!${count}"
staged ="+${count}"
renamed ="»"
deleted ="✘"

[golang]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
symbol = "☸"
style = "bg:purple fg:white"
format = '[ $symbol $context( \($namespace\)) ]($style)'
disabled = false

[nodejs]
symbol = ""
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:green"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[status]
disabled = false
format = '$symbol$status '
symbol = "[](red) "
success_symbol = "[](green) "
style = "red"

[sudo]
style = "bold green"
disabled = false

[terraform]
symbol = "ﳼ "
style = "bg:green"
format = '[ $symbol $workspace ]($style)'
