# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$username\
$hostname\
[ ](fg:color_orange bg:color_yellow)\
$directory\
[ ](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[ ](fg:color_aqua bg:color_blue)\
$golang\
$terraform\
[](fg:color_blue bg:color_bg3)\
$kubernetes\
[ ](fg:color_bg3 bg:color_bg1)\
$status\
[ ](fg:color_bg1)"""

# Disable the blank line at the start of the prompt
add_newline = false
continuation_prompt = "[ ](fg:green)"
command_timeout = 750


palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = false
style_user = "bg:color_orange fg:color_fg0"
style_root = "bold bg:color_orange fg:bright-white"
format = '[ $user]($style)'

[hostname]
ssh_only = true
format = "[@$hostname ](bg:purple)"
disabled = false


[character] # The name of the module we are configuring is "character"
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[directory]
style = "fg:color_bg1 bg:color_yellow"
format = "[$path ]($style)[$read_only]($read_only_style)"
read_only = " "
read_only_style = "fg:color_fg0 bg:color_bg1"
truncation_length = 5
truncate_to_repo = true
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[$symbol $branch ]($style)'
ignore_branches = ['master', 'main']

[git_status]
style = "fg:color_fg0 bg:color_aqua"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
format = '[$ahead_behind$modified$staged$untracked$conflicted ]($style)'
ignore_submodules = true

conflicted ="=${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
up_to_date = ""
untracked = "?${count}"
stashed = "$"
modified = "!${count}"
staged = "+${count}"
renamed = "»"
deleted = "x"

[golang]
symbol = ""
style = "fg:color_fg0 bg:color_blue"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:color_fg0 bg:color_blue"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
symbol = "☸"
style = "bg:color_bg3 fg:color_yellow"
format = '[ $symbol $context( \($namespace\)) ]($style)'
disabled = false

[nodejs]
symbol = ""
style = "fg:color_fg0 bg:color_blue"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "fg:color_fg0 bg:color_blue"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "fg:color_fg0 bg:color_blue"
format = '[ $symbol ($version) ]($style)'

[status]
disabled = false
format = '[$symbol$status ]($style)'
symbol = "[](fg:red bg:color_bg1) "
success_symbol = "[](fg:green bg:color_bg1) "
style = "fg:color_fg0 bg:color_bg1"

[sudo]
symbol = "󰘶"
format = "[$symbol ]($style)"
style = "bg:color_orange fg:color_bg1"
disabled = true

[terraform]
symbol = "󱁢"
style = "fg:color_fg0 bg:color_blue"
format = '[ $symbol $workspace ]($style)'
