# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

#[](bg:blue fg:245)\
format = """
[](blue)\
$username\
$directory\
[ ](fg:blue bg:yellow)\
$git_branch\
$git_status\
[ ](fg:yellow bg:green)\
$golang\
$java\
$nodejs\
$python\
$terraform\
[ ](fg:green)\
"""

right_format = """
$status\
[\ue0b2](fg:purple )\
$kubernetes\
[\ue0b4](fg:purple )\
"""
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = false
style_user = "bold bg:blue"
style_root = "bold bg:blue fg:88"
format = '[$user:]($style)'

[directory]
style = "bg:blue fg:230"
format = "[$path ]($style)[$read_only]($read_only_style)"
read_only = " "
truncation_length = 5
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:yellow"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
symbol = "☸"
style = "bg:purple"
format = '[ $symbol $context( \($namespace\)) ]($style)'
disabled = false

[nodejs]
symbol = ""
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:green"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[status]
disabled = false
format = '$symbol$status '
symbol = "[](red) "
success_symbol = "[](green) "
style = "red"

[sudo]
style = "bold green"
disabled = false

[terraform]
symbol = "ﳼ "
style = "bg:green"
format = '[ $symbol $workspace ]($style)'
